name: Pypi Windows  

on:
  push:
    paths: 
      - "**.py"
      - "*.yml"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [  "3.10" ,"3.11", "3.12", "3.13"]

    steps:
      - name: Set UTF-8 Encoding
        run: echo "PYTHONUTF8=1" >> $GITHUB_ENV


      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install uv  
          uv venv
          .venv\Scripts\activate
          uv pip install openpyxl>=3.1.5 pandas>=2.2.3 pdfplumber>=0.11.6 requests>=2.32.3
      - name: Run tests
        run: |
          pytest -v
      
      
